### ISSUE TITLE
Green privacy dot only visible if no app is open

### ISSUE THREAD

**Issue by z411** [AOSPA/Tracker#12]
**Describe the bug**
When the microphone is being used, the green privacy dot at the top right corner should always be visible.
But in latest releases it disappears when I open an app. It only appears again if I minimize all apps.

**To Reproduce**
1. Let any app that uses the microphone running (a call in Telegram/Discord for example)
2. Open any other app

**Expected behavior**
The green dot should always be visible while the mic is being in use

**Actual behavior**
The green dot disappears when I open any app, as if the app activity was on top of the dot.
Only if I minimize all apps (ie. home button) the dot is visible.

It also appears briefly if I slowly swipe down the status bar.

**Screenshots**
A video is better to visualize the problem:

https://github.com/AOSPA/Tracker/assets/1988512/5c0d37ed-7092-411d-95a2-878c664418b1

**Device (please complete the following information):**
 - Manufacturer and Model: Xiaomi Redmi Note 11 (spes)
 - Build: Topaz 3

**Additional context**
It seems the problem is only present in this device. The padding looks fine.
The problem happens ever since Beta 2.

**Comment by z411** [comment]
While trying to debug the issue I noticed that the green dot works properly if I change the following parameters from the SpesFrameworksOverlay:

* `config_fillMainBuiltInDisplayCutout` to false
* All `rounded_corner_radius` parameters to 0px

Even if I set the corner_radius to 1px the green dot will stop working. If I enable the cutout fill it also breaks.

**Comment by xboxfanj** [comment]
Very weird, I saw your post.  I'll let ChrisL7 know and he'll take a look.

**Comment by z411** [comment]
Fixed by stitch prop.
