### ISSUE TITLE
Separated Network Toggle 

### ISSUE THREAD

**Issue by ghost** [AOSPA/Tracker#14]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Separated toggles for cellular data & WiFi in QS 
I know your policy is to keep it simple & minimal but turning on/off Data could be more easier with this for they who don't have WiFi 

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by ghost** [comment]
+1

**Comment by xboxfanj** [comment]
We did do this.
