### ISSUE TITLE
Recognize links in text

### ISSUE THREAD

**Issue by ghost** [AOSPA/Tracker#7]
**Describe the bug**
Links cant be recognized automatically when trying to copy in text 

**To Reproduce**
1. copy some links and paste in a text file 
2. open that text file with any text viewer or text editor
3. try to copy the link with touch and holding part of it

**Expected behavior**
with just holding a word in that link , it should automatically select that link.

**Actual behavior**
it cant recognize its a link and only selects that word.

**Screenshots**
![photo_2023-05-25_11-34-37](https://github.com/AOSPA/Tracker/assets/134587729/20f20c0a-f4a3-4022-9d9c-13eff1712028)

**Device (please complete the following information):**
Manufacturer and Model: Redmi 8A (Mi439:Redmi 7A/8/8A/8A Dual)
Build: Topaz 2

**Additional context**
i think this problem can be because of a broken service related to google system intelligence because with deleting google system intelligence from
 /product/priv-app/DevicePersonalizationPrebuiltPixel2020  
it will be fixed and links will be recognized automatically !
by the way , this issue also exist in superior OS but when our maintainer built an unofficial build with adding pixel launcher as default launcher , it fixed ! (in same version without pixel launcher links cant be recognized automatically )

**Comment by xboxfanj** [comment]
@gotenksIN is this fixed in new GMS?

**Comment by me3yed** [comment]
> @gotenksIN is this fixed in new GMS?

Not yet, I've tried and still not fixed

**Comment by Jprimero15** [comment]
Fixed with this: https://github.com/AOSPA/android_vendor_aospa/commit/742635f17a4e5d02e497219eb48da2355d24b47a
